### ISSUE TITLE
Failed to call make.exe

### ISSUE THREAD

**Issue by EnyuZhuang** [damogranlabs/VS-Code-STM32-IDE#12]
When I run the update.py, it failed 
> Traceback (most recent call last):
>   File "ideScripts/update.py", line 48, in <module>
>     makefileData = makefile.getMakefileData(makeExePath, gccExePath)
>   File "***\ideScripts\up                                                                                                                                                                                               dateMakefile.py", line 89, in getMakefileData
>     makeExePath, gccExePath, self.mkfStr.projectName)[0]
>   File "***\ideScripts\up                                                                                                                                                                                               dateMakefile.py", line 361, in getMakefileVariable
>     proc = Popen(arguments, stdout=PIPE)
>   File "***\AppData\Local\Programs\Python\Python37\lib\subprocess.py",                                                                                                                                                                                                line 775, in __init__
>     restore_signals, start_new_session)
>   File "***\AppData\Local\Programs\Python\Python37\lib\subprocess.py",                                                                                                                                                                                                line 1178, in _execute_child
>     startupinfo)
> PermissionError: [WinError 5] Access is denied

My quick fix was to add the file name make.exe to the getMakefileVariable funtion in updateMakefile.py
> arguments = [makeExePath **+ "/make.exe"**, gccPath, printStatement]

I am not sure whether it was a correct fix for the problem that I had.

**Comment by EnyuZhuang** [comment]
I found the reason that I run into this problem. I did not include the "make.exe" when I entered "path or command for 'make executable (make.exe)':".

Sorry for the inconvenience.
